Sync templates

diff --git a/.github/workflows/linters.yml b/.github/workflows/linters.yml
--- a/.github/workflows/linters.yml
+++ b/.github/workflows/linters.yml
@@ -29,3 +29,14 @@ jobs:
       prettierPlugins: ${{ vars.INSTALL_PRETTIER_PLUGINS }}
     secrets:
       PAT_ACTION_CI: ${{ secrets.PAT_ACTION_CI }}
+
+  do-not-merge:
+    name: Disable merging on label
+    if: ${{ contains(github.event.pull_request.labels.*.name, 'do not merge') }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for label
+        run: |
+          echo "Pull request is labeled as 'do not merge'"
+          echo "This workflow fails so that the pull request cannot be merged"
+          exit 1
